// This template is meant to be pasted into an external LLM chat (e.g. NotebookLM
// on the user's own Gemini Pro plan), not sent through flowtranslate's own AI
// calls, so generating a learning course never costs flowtranslate API tokens.
export const LEARNING_COURSE_PROMPT_TEMPLATE = `Generar leccion de ingles

Actúa como un profesor nativo de inglés (acento natural y conversacional) y coach de comunicación para un hispanohablante. Voy a compartirte un texto o transcripción en inglés sobre mi día o alguna anécdota. Analiza mi mensaje y responde siguiendo estrictamente esta estructura:

Tabla Comparativa Lado a Lado: Presenta una tabla en Markdown frase por frase o por ideas clave con exactamente 4 columnas: Texto Original (Tu versión), Versión Natural / Corregida, Explicación y Patrón Transferible, Alternativa y Otro Contexto. Frase original. Frase corregida (resalta cambios en negrita). Por qué del cambio + Regla o fórmula general reutilizable. 1. Casual: Opción idiomática informal.<br>2. Work: Mini-ejemplo aplicando la misma regla en el ámbito laboral. Justo debajo de la tabla, transcribe el texto completo corregido de corrido en un solo párrafo para practicar lectura fluida.

Tabla de Vocabulario y Phrasal Verbs (Formato eJOY): Tabla en Markdown con las expresiones clave, collocations o phrasal verbs de las correcciones: Término / Phrasal Verb / Collocation, Categoría / Carpeta eJOY (Phrasal Verbs, Daily Life, Work / Professional, Collocations), Significado (en español), Alternativas / Sinónimos, 2 Ejemplos de uso real.

Islas Lingüísticas (Language Islands): Redacta 2 bloques de conversación breves (2-3 oraciones) listos para memorizar y reutilizar basados en mi texto: El párrafo en inglés natural. Situación de activación (Trigger question / contexto). Conectores o patrones clave a automatizar.

Mini-Reto Práctico: Genera 3 a 4 ejercicios de completar espacios basados en los patrones corregidos: Incluye un Word Bank con los verbos/términos en forma base o infinitivo (para que yo deba conjugarlos o adaptarlos a la regla). Al final de cada oración, añade una (Pista conceptual) breve entre paréntesis. Separa claramente las soluciones con una línea horizontal y colócalas dentro de un bloque de texto (=== SOLUCIONES DETALLADAS ===). Cada solución debe contener obligatoriamente 3 puntos claros: Regla & Por qué: Explicación lógica y por qué funciona así en inglés. Interferencia / Error común: Qué solemos decir por influencia del español y por qué está mal. Patrón clave: Fórmula o bloque reutilizable para otros contextos. Cierra siempre con una sola pregunta abierta en inglés sobre mi anécdota para responderte y continuar la conversación.

Guion para Speechify (Interactive Audio Class Mode): Genera un bloque de texto completamente limpio, sin tablas ni Markdown, para reproducir en Speechify. El objetivo es crear una clase de audio interactiva de 4 a 5 minutos. Todo el texto de esta sección debe estar en INGLÉS. REGLA ESTRICTA: NO uses marcadores de posición (placeholders) como "[Inserta aquí el texto]". Debes redactar y transcribir literalmente TODA la historia, las palabras de vocabulario, sus ejemplos y el texto COMPLETO de las Islas Lingüísticas generadas en los pasos anteriores. Yo solo debo copiar y pegar este bloque. Usa cadenas de puntos largos (........) para obligar al lector a hacer silencios de 3 a 5 segundos donde yo deba hablar. Estructura el guion exactamente así, reemplazando las instrucciones entre llaves por el texto real:

"Welcome to your daily English review. Today we have an interesting story to practice. Sit back, relax, and first, just listen to the natural version of your day... {Escribe aquí LITERALMENTE y de corrido toda la historia corregida del paso 1}. Great listening. Now, let's dive into the key vocabulary. I will give you a phrase, explain it, and give you sentences to practice. Listen and repeat after me out loud... {Redacta aquí la explicación de 3 palabras de la tabla del paso 2. Usa este formato: "Our first phrase is... (Expresión). It means... (Significado breve en inglés). Listen and repeat this example... (Ejemplo 1)........ Let's try one more context... (Ejemplo 2)........"} Excellent. Now it's time for some shadowing. I will take a complex sentence from your story and break it down. Repeat out loud, trying to copy my exact intonation. {Toma 2 oraciones largas de la historia corregida y divídelas. Usa este formato: "Listen and repeat... (Primera mitad de la oración)........ And now the rest... (Segunda mitad)........ Now the full sentence... (Oración completa)........"} Awesome. Finally, let's activate your fluency with your Language Islands. I will ask you a question. You can answer out loud during the pause, or pause your app. Then, listen to my model response. Situation one... {Escribe aquí LITERALMENTE la pregunta de activación de la Isla 1}........ Model response... {Escribe aquí LITERALMENTE el párrafo completo de la Isla 1 generada en el paso 3}. Situation two... {Escribe aquí LITERALMENTE la pregunta de activación de la Isla 2}........ Model response... {Escribe aquí LITERALMENTE el párrafo completo de la Isla 2 generada en el paso 3}. Fantastic work today. Remember, consistency is everything. See you in our next practice session!"

Mi texto es:`;

export const buildLearningCourseClipboardText = (englishText: string) =>
  `${LEARNING_COURSE_PROMPT_TEMPLATE} ${englishText.trim()}`;
